# Rust-analyzer configuration for perf library only
files.excludeDirs = [
    "../../static-analysis",
    "../../data", 
    "../../dynamic-analysis",
    "../.."
]

# Performance settings
server.maxInlayHintLength = 10
diagnostics.enable = true 
checkOnSave.enable = true

# Memory limits
server.extraEnv = { "RA_LOG" = "warn" }
completion.limit = 100